name: burger_shop
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  provider:
  brasil_fields:
  date_time_picker:
  flux_validator_dart:
  dio:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - lib/core/assets/images/add.png
    - lib/core/assets/images/Saly-11.png
    - lib/core/assets/images/ImageLogo.png
    - lib/core/assets/images/hidden.png
    - lib/core/assets/images/arrow-down.png
    - lib/core/assets/images/password.png
    - lib/core/assets/images/check.png
    - lib/core/assets/images/dollar-sign.png
    - lib/core/assets/images/Burger-Isometric.png
    - lib/core/assets/images/search.png
    - lib/core/assets/images/profile.png
    - lib/core/assets/images/BurgerLoading.png
    - lib/core/assets/images/Saly-13.png
    - lib/core/assets/images/Show.png
    - lib/core/assets/images/tag-price.png
    - lib/core/assets/images/dashboard.png
    - lib/core/assets/images/check-circle.png
    - lib/core/assets/images/check-off.png
    - lib/core/assets/images/pen.png
    - lib/core/assets/images/logoLetter.png
    - lib/core/assets/images/Ellipse-8.png
    - lib/core/assets/images/ImageBurger.png
    - lib/core/assets/images/PathPlus.png
    - lib/core/assets/images/ArrowDownRed.png
    - lib/core/assets/images/ArrowUpGreen.png
    - lib/core/assets/images/StrokeRight.png
    - lib/core/assets/images/Ketchup.png
    - lib/core/assets/images/IllustrationDica.png
    - lib/core/assets/images/SucessoCadastro.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Geomanist
      fonts:
        - asset: lib/core/assets/geomanist-regular-webfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

